export const PUBLIC_ROUTES = [
  '/',
  '/welcome',
  '/about',
  '/developers',
  '/privacy-policy',
  '/download',
  '/donate',
  '/whatsnew',
  '/community',
  '/contact',
  '/roadmap',
  '/features',
  '/ad-blocking',
  '/tracking-protection',
  '/permissions',
  '/terms-of-service',
  '/cookie-policy',
  '/licenses',
  '/blog',
] as const
